# Generated by Django 4.2.11 on 2024-07-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.IntegerField(unique=True),
        ),
    ]
